---
name: Integration Tests
run-name: >
  Integration Tests [${{
   github.event.client_payload.distinct_id &&
   github.event.client_payload.distinct_id ||
   inputs.distinct_id && inputs.distinct_id || 'N/A' }}]

on:
  repository_dispatch:
    types:
      - repository-dispatch
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "Distinct ID"
        required: true
      placeholder:
        description: "Placeholder Input"
        required: false
        default: 'placeholder'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello World 👋"
