---
name: Integration Tests
run-name: >
  Integration Tests [${{
    github.event.client_payload.distinct_id &&
    github.event.client_payload.distinct_id ||
    inputs.distinct_id && inputs.distinct_id || 'N/A' }}]

on:
  repository_dispatch:
    types:
      - repository-dispatch
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "Distinct ID"
        required: false
      string-type:
        description: An input of type 'String'
        required: true
        type: string
      number-type:
        description: An input of type 'Number'
        type: number
      boolean-type:
        description: An input of type 'Boolean'
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Validate workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "${{ inputs.string-type }}" # "placeholder"
          if [[ "${{ inputs.number-type }}" -gt -1 ]]; then echo "游릭"; fi
          if [[ "${{ inputs.boolean-type }}" == "true" ]]; then echo "游릭"; fi
      - name: Validate repository_dispatch
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "${{ github.event.client_payload.string-type }}" # "placeholder"
          if [[ "${{ github.event.client_payload.nested.number-type }}" -gt -1 ]]; then echo "游릭";
          if [[ "${{ github.event.client_payload.nested.boolean-type }}" == "true" ]]; then echo "游릭";
